---

- name: enable fuse service
  systemd:
    name: "{{ app_name }}.service"
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
