---

- name: create a directory for target application
  file:
    owner: "{{ fuse_user }}"
    group: "{{ fuse_group }}"
    path: "{{ app_deployment_directory }}"
    state: directory
  become: yes
  tags: deployment

- name: copy application jar from url
  get_url:
    owner: "{{ fuse_user }}"
    group: "{{ fuse_group }}"
    url: "{{ app_artifact_url }}"
    dest: "{{ app_deployment_directory }}/app.jar"
    mode: 0644
  become: yes
  when: app_artifact_url is defined
  tags: deployment

- name: copy application jar from local file
  copy:
    owner: "{{ fuse_user }}"
    group: "{{ fuse_group }}"
    src: "{{ app_artifact_path }}"
    dest: "{{ app_deployment_directory }}/app.jar"
    mode: 0644
  become: yes
  when: app_artifact_url is not defined and app_artifact_path is defined
  tags: deployment

- name: stop target application service
  service:
    name: "{{ app_name }}.service"
    state: stopped
  become: yes
  tags: deployment

- name: create symlink to the latest target application folder
  file:
    src: "{{ app_deployment_directory }}"
    dest: "{{ app_directory }}/latest"
    state: link
  become: yes
  tags: deployment

- name: start fuse service
  systemd:
    name: "{{ app_name }}.service"
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
  tags: deployment
