---

- name: fuse user group
  group:
    name: "{{ fuse_group }}"
    state: present
  become: yes
  tags: environment

- name: fuse user
  user:
    name: "{{ fuse_user }}"
    group: "{{ fuse_group }}"
  become: yes
  tags: environment

- name: create org directory
  file:
    owner: root
    group: root
    path: "{{ org_base_directory }}"
    state: directory
    mode: 0755
  become: yes
  tags: environment

- name: create apps directory
  file:
    owner: "{{ fuse_user }}"
    group: "{{ fuse_group }}"
    path: "{{ fuse_apps_base_directory }}"
    state: directory
    mode: 0775
  become: yes
  tags: environment
