---

- name: is firewalld installed
  command: systemctl status firewalld
  register: firewalld_status
  failed_when: false
  changed_when: false
  tags: provisioning

- name: is iptables installed
  command: systemctl status iptables
  register: iptables_status
  failed_when: false
  changed_when: false
  tags: provisioning

- name: open service port in firewalld
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ app_service_port }}"
    - "{{ app_health_port }}"
  when: firewalld_status.rc == 0
  notify:
  - restart firewalld
  tags: provisioning

- name: open service port in iptables for future session
  lineinfile:
    insertbefore: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT"
    state: present
    dest: /etc/sysconfig/iptables
    regexp: "^-A INPUT .* --dport {{ item}} .* ACCEPT"
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - "{{ app_service_port }}"
    - "{{ app_health_port }}"
  when: iptables_status.rc == 0 and firewalld_status.rc != 0
  tags: provisioning

- name: open service port in iptables for current session
  iptables:
    action: insert
    protocol: tcp
    destination_port: "{{ item }}"
    state: present
    chain: INPUT
    jump: ACCEPT
  with_items:
    - "{{ app_service_port }}"
    - "{{ app_health_port }}"
  when: iptables_status.rc == 0 and firewalld_status.rc != 0
  tags: provisioning
